### PR TITLE
Add Docker CI

### PR DESCRIPTION
**Pull request by aravindvnair99**
This CI analyses PRs for build failures. Helpful for catching PRs such as:
- https://github.com/w9jds/firebase-action/pull/99
- https://github.com/w9jds/firebase-action/pull/100

And validating fixes the same such as:
- https://github.com/w9jds/firebase-action/pull/101 (If this is merged, build will pass)

### CODE REVIEW

**Comment by aravindvnair99** [comment]
@w9jds I recommend marking this as a [required check](https://github.com/w9jds/firebase-action/settings/branches) for PRs for catching build failures at an earlier stage.

**Comment by w9jds** [comment]
Yeah this is my bad, It was 2 am and I didn't test it myself. This is good, Thanks.

**Comment by aravindvnair99** [comment]
> Yeah this is my bad, It was 2 am and I didn't test it myself. This is good, Thanks.

No worries, happy to help! :)

**Comment by aravindvnair99** [comment]
> Yeah this is my bad, It was 2 am and I didn't test it myself. This is good, Thanks.

No worries @w9jds, happy to help! :)

**Pull request merged**
